linters:
  enable:
    - structcheck
    - varcheck
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - golint
    - ineffassign
    - vet
    - unused
    - misspell
  disable:
    - errcheck

run:
  deadline: 4m
  skip-dirs:
    - images
    - out
    - script
    - vendor
