[plugins.stargz]
root_path = "/var/lib/containerd-stargz-grpc/"
disable_verification = false

[plugins.stargz.blob]
check_always = true

[[plugins.stargz.resolver.host."registry-integration.test".mirrors]]
host = "registry-alt.test:5000"
insecure = true
