plugin_dir = "/opt/containerd/plugins"
[plugins]
  [plugins.linux]
    runtime_root = "/runtime_root"
    plugin_dir = "/var/lib/containerd/plugins"
    snapshotter = "overlayfs"
  [plugins.stargz]
    insecure = ["127.0.0.1", "localhost"]
    cache_chunk_size = 50000
    lru_max_entry = 5000
    http_cache_type = "directory"
    filesystem_cache_type = "directory"
