version: "3"
services:
  containerd:
    build: containerd
    container_name: containerd
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /go/src/github.com/containerd/containerd
    environment:
    - GO111MODULE=off
    - NO_PROXY=127.0.0.1,localhost,registry2:5000
    - HTTP_PROXY=${HTTP_PROXY}
    - HTTPS_PROXY=${HTTPS_PROXY}
    - http_proxy=${http_proxy}
    - https_proxy=${https_proxy}
    - GOPATH=/go
    tmpfs:
    - /var/lib/containerd
    - /tmp
    volumes:
    - /dev/fuse:/dev/fuse
    - "${GOPATH}/src/github.com/ktock/remote-snapshotter:/go/src/github.com/ktock/remote-snapshotter"
  registry2:
    image: registry:2
    container_name: registry2
    environment:
    - HTTP_PROXY=${HTTP_PROXY}
    - HTTPS_PROXY=${HTTPS_PROXY}
    - http_proxy=${http_proxy}
    - https_proxy=${https_proxy}
