version: "3"
services:
  containerd_demo:
    build: .
    container_name: containerd_demo
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /go/src/github.com/containerd/stargz-snapshotter
    entrypoint: /bin/bash
    environment:
    - NO_PROXY=127.0.0.1,localhost,registry2:5000
    - HTTP_PROXY=${HTTP_PROXY}
    - HTTPS_PROXY=${HTTPS_PROXY}
    - http_proxy=${http_proxy}
    - https_proxy=${https_proxy}
    - GOPATH=/go
    tmpfs:
    - /var/lib/containerd
    - /var/lib/containerd-stargz-grpc
    - /run/containerd-stargz-grpc
    - /tmp:exec,mode=777
    volumes:
    - /dev/fuse:/dev/fuse
    - "${GOPATH}/src/github.com/containerd/stargz-snapshotter:/go/src/github.com/containerd/stargz-snapshotter:ro"
  registry2:
    image: registry:2
    container_name: registry2
    environment:
    - HTTP_PROXY=${HTTP_PROXY}
    - HTTPS_PROXY=${HTTPS_PROXY}
    - http_proxy=${http_proxy}
    - https_proxy=${https_proxy}
