name: Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build
    steps:
    - uses: actions/checkout@v2
    - name: Build all
      run: ./script/util/make.sh build -j2
  test:
    runs-on: ubuntu-18.04
    name: Test
    steps:
    - uses: actions/checkout@v2
    - name: Test all
      run: ./script/util/make.sh test-all -j2
  check:
    runs-on: ubuntu-18.04
    name: Check
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Check all
      run: ./script/util/make.sh install-check-tools check
  integration:
    runs-on: ubuntu-18.04
    name: Integration
    steps:
    - uses: actions/checkout@v2
    - name: Run integration test
      run: make integration
  test-optimize:
    runs-on: ubuntu-18.04
    name: Optimize
    steps:
    - uses: actions/checkout@v2
    - name: Run test for optimize subcommand of ctr-remote
      run: make test-optimize
  test-pullsecrets:
    runs-on: ubuntu-18.04
    name: PullSecrets
    steps:
    - uses: actions/checkout@v2
    - name: Run test for pulling image from private registry on Kubernetes
      run: make test-pullsecrets
  test-cri:
    runs-on: ubuntu-18.04
    name: CRIValidation
    steps:
    - uses: actions/checkout@v2
    - name: Varidate the runtime through CRI
      run: make test-cri
